set(XGBOOST_CMAKE_ARGS
  XGBOOST_USE_HALF=ON
  XGBOOST_DO_LEAN=${XGBOOSTER_DO_LEAN}
  XGBOOST_USE_CEREAL=${XGBOOSTER_SERIALIZE_WITH_CEREAL}
  )

hunter_config(xgboost GIT_SUBMODULE "src/3rdparty/xgboost" CMAKE_ARGS ${XGBOOST_CMAKE_ARGS})

hunter_config(cereal GIT_SUBMODULE "src/3rdparty/cereal" CMAKE_ARGS JUST_INSTALL_CEREAL=ON)
